# Caso de estudio 2: optimización de la composición de una barra nutricional

- Queremos formular una barra nutricional con una mezcla específica de ingredientes para cumplir con ciertos requisitos nutricionales, mientras se mantiene dentro de un presupuesto.
- Cada ingrediente tiene un costo por unidad y contribuye a la barra con una cantidad específica de nutrientes.

## Datos de ingredientes

| Ingrediente           | Costo por gramo | Proteínas (g/100g) | Carbohidratos (g/100g) | Grasas (g/100g) | Calorías (kcal/100g) |
|---------------------------|---------------------|------------------------|----------------------------|---------------------|--------------------------|
| **Proteína de Suero**         | \$0.10               | 80                     | 5                          | 2                   | 350                      |
| **Avena**                 | \$0.02               | 15                     | 60                         | 6                   | 370                      |
| **Mantequilla de Almendra**| \$0.15               | 25                     | 20                         | 50                  | 600                      |
| **Azúcar**                | $0.01               | 0                      | 100                        | 0                   | 400                      |

## Rangos

| **Ingrediente**           | **Rango de Cantidad (gramos)** |
|---------------------------|-------------------------------|
| **Proteína de Suero**     | 10 - 50                       |
| **Avena**                 | 20 - 100                      |
| **Mantequilla de Almendra**| 5 - 30                       |
| **Azúcar**                | 0 - 20                        |



## Variables

- $v_1$: Cantidad de proteína de suero en la barra (en gramos)
- $v_2$: Cantidad de avena en la barra (en gramos)
- $v_3$: Cantidad de mantequilla de almendra en la barra (en gramos)
- $v_4$: Cantidad de azúcar en la barra (en gramos)

## Restricciones

  - **Proteínas**: Al menos 20 gramos
  - **Carbohidratos**: Al menos 30 gramos
  - **Grasas**: Al menos 10 gramos
  - **Calorías**: Entre 250 y 350 kcal


## Función Objetivo

- Minimizar el costo total de la barra:

  $$
  \text{Costo Total} = 0.10v_1 + 0.02v_2 + 0.15v_3 + 0.01v_4
  $$

Donde:
- $v_1$: Cantidad de proteína de suero en la barra (en gramos).
- $v_2$: Cantidad de avena en la barra (en gramos).
- $v_3$: Cantidad de mantequilla de almendra en la barra (en gramos).
- $v_4$: Cantidad de azúcar en la barra (en gramos).

## Función de Aptitud

$$
   \text{Aptitud} = \frac{1}{\text{Costo Total} + \text{Penalización}}
$$

Donde la penalización es una suma de las penalizaciones aplicadas por incumplir los requisitos nutricionales y el rango de calorías.

- **Penalización por no cumplir los requerimientos**: Si la mezcla no cumple con alguno de los requisitos nutricionales, se aplica una penalización al costo total:
     - Penalización por cada gramo de proteína faltante.
     - Penalización por cada gramo de carbohidrato o grasa excedente o faltante.
     - Penalización por cada caloría fuera del rango deseado.




In [ ]:
#!pip install pandas numpy gdown

### 1. Importación de bibliotecas y lectura de datos

- Primero, importamos las bibliotecas necesarias.
- Leemos los datos desde un archivo Excel que contiene información sobre los ingredientes y los rangos de valores permitidos para cada ingrediente.
- Extraemos la información sobre los ingredientes, costos, proteínas, carbohidratos, grasas y calorías.


In [ ]:
import gdown
import pandas as pd
import numpy as np

# URL del archivo en Google Drive
file_id = '15QuX1fliafQbrJApky6Z0SUIli0dxXo6'
url = f'https://drive.google.com/uc?id={file_id}'
filename = 'barra_nutricional.xlsx'

# Descargar el archivo
gdown.download(url, filename, quiet=False)

# Leer datos desde el archivo descargado
ingredientes_df = pd.read_excel(filename, sheet_name='ingredientes')
rangos_df = pd.read_excel(filename, sheet_name='rangos')

# Datos de ingredientes
ingredientes = ingredientes_df['Ingrediente'].values
precios = ingredientes_df['Costo'].values
proteinas = ingredientes_df['Proteínas (g/100g)'].values
carbohidratos = ingredientes_df['Carbohidratos (g/100g)'].values
grasas = ingredientes_df['Grasas (g/100g)'].values
calorias = ingredientes_df['Calorías (kcal/100g)'].values

# Rangos
rango_minimos = rangos_df['Min'].values
rango_maximos = rangos_df['Max'].values

Downloading...
From: https://drive.google.com/uc?id=15QuX1fliafQbrJApky6Z0SUIli0dxXo6
To: /content/barra_nutricional.xlsx
100%|██████████| 13.2k/13.2k [00:00<00:00, 24.9MB/s]


### 2. Definición de parámetros del algoritmo genético

- Establecemos los parámetros básicos para el algoritmo genético, como el tamaño de la población, el número de generaciones, y las probabilidades de cruce y mutación.


In [ ]:

# Parámetros del algoritmo genético
n_ingredientes = len(ingredientes)
poblacion_size = 20
generaciones = 100
mutacion_prob = 0.2
cruce_prob = 0.7

### 3. Función de aptitud: Cálculo de la información nutricional y costo de producción

- En esta parte necesitamos una función que calcule la cantidad total de proteínas, carbohidratos, grasas y calorías basadas en los valores del cromosoma.

- El costo total según el gramaje de cada ingrediente.

- Penalizaciones si el cromosoma no cumple con ciertos requisitos nutricionales y de calorías.

In [ ]:
# Información nutricional
def calcular_nutricion(cromosoma):
    cromosoma_cada_100 = cromosoma / 100
    proteina_total = np.sum(cromosoma_cada_100 * proteinas)
    carbohidrato_total = np.sum(cromosoma_cada_100 * carbohidratos)
    grasa_total = np.sum(cromosoma_cada_100 * grasas)
    calorias_total = np.sum(cromosoma_cada_100 * calorias)
    return proteina_total, carbohidrato_total, grasa_total, calorias_total

# Función de aptitud
def calcular_aptitud(cromosoma):
    proteina_total, carbohidrato_total, grasa_total, calorias_total = calcular_nutricion(cromosoma)

    # Penalización
    penalizacion_proteinas = max(0, 20 - proteina_total)
    penalizacion_carbohidratos = max(0, 30 - carbohidrato_total) if carbohidrato_total < 30 else max(0, carbohidrato_total)
    penalizacion_grasas = max(0, 10 - grasa_total)
    penalizacion_calorias = max(0, 250 - calorias_total) if calorias_total < 250 else max(0, calorias_total - 350)

    penalizacion_total = penalizacion_proteinas + penalizacion_carbohidratos + penalizacion_grasas + penalizacion_calorias
    costo_total = np.sum(cromosoma * precios)
    #print(costo_total, penalizacion_total)
    aptitud = 1/ (costo_total + penalizacion_total)

    return aptitud


### 5. Inicialización de la población

- La función `inicializar_poblacion` crea una población inicial de soluciones (cromosomas) generando valores aleatorios dentro de los rangos permitidos para cada ingrediente.


In [ ]:
# Inicializar población
def inicializar_poblacion(rangos_min, rangos_max, poblacion_size, n_ingredientes):
    return np.random.uniform(rangos_min, rangos_max, (poblacion_size, n_ingredientes))

poblacion_prueba = inicializar_poblacion(rango_minimos, rango_maximos, 5, n_ingredientes)
print(poblacion_prueba)

[[31.29620318 68.96561962 28.30065327 17.31118064]
 [12.74571487 23.66522463 22.92546082 17.532213  ]
 [21.14434064 85.30352175 17.20559845 12.25851971]
 [43.8731092  38.45802115 20.96146729 12.1870949 ]
 [49.62012689 54.5075568  17.30294994  0.78581214]]


### 6. Selección de Padres
- Este proceso selecciona dos individuos de la población con probabilidades proporcionales a sus aptitudes. Así, los individuos "mejores" tienen más probabilidades de ser seleccionados como padres.


In [ ]:
# Selección de padres
def seleccion(poblacion):
    aptitudes = np.array([calcular_aptitud(ind) for ind in poblacion])
    total_aptitud = np.sum(aptitudes)

    # Evitar división por cero si todas las aptitudes son cero
    if total_aptitud == 0:
        probabilidades = np.ones(len(poblacion)) / len(poblacion)
    else:
        probabilidades = aptitudes / total_aptitud

    # Selecciona dos individuos con probabilidad proporcional a su aptitud
    indices = np.random.choice(len(poblacion), size=2, p=probabilidades)
    return poblacion[indices]


### 7. Cruce de Padres
- Esta función implementa el cruce entre dos padres. Si se cumple la probabilidad de cruce, se intercambian segmentos de los padres para generar dos nuevos hijos.

In [ ]:
# Cruce de dos padres
def cruce(padre1, padre2):
    if np.random.rand() < cruce_prob:
        punto_cruce = np.random.randint(1, n_ingredientes)
        hijo1 = np.concatenate((padre1[:punto_cruce], padre2[punto_cruce:]))
        hijo2 = np.concatenate((padre2[:punto_cruce], padre1[punto_cruce:]))
        return hijo1, hijo2
    else:
        return padre1, padre2


### 8. Mutación
- La mutación introduce variación en un individuo al modificar uno de sus genes. Luego, se asegura que el valor mutado se mantenga dentro de los rangos permitidos usando `np.clip`.


In [ ]:
# Mutación
def mutacion(individuo, rangos_min, rangos_max):
    if np.random.rand() < mutacion_prob:
        punto_mutacion = np.random.randint(n_ingredientes)
        individuo[punto_mutacion] += np.random.standard_normal()
    return np.clip(individuo, rangos_min, rangos_max)


### 9. Algoritmo Genético completo

- La población inicial se somete a un ciclo de generaciones, donde se seleccionan padres, se generan nuevos hijos mediante cruce y mutación, y se realiza un reemplazo parcial con la nueva población.
- Después de cada generación, se selecciona el mejor individuo (la mejor solución) y se imprime su aptitud.


In [ ]:
# Algoritmo genético
def algoritmo_genetico():
    poblacion = inicializar_poblacion(rango_minimos, rango_maximos, poblacion_size, n_ingredientes)
    for generacion in range(generaciones):
        nueva_poblacion = []
        for _ in range(poblacion_size // 2):
            padre1, padre2 = seleccion(poblacion)
            hijo1, hijo2 = cruce(padre1, padre2)
            nueva_poblacion.append(mutacion(hijo1, rango_minimos, rango_maximos))
            nueva_poblacion.append(mutacion(hijo2, rango_minimos, rango_maximos))
        nueva_poblacion = np.asarray(nueva_poblacion)
        # Reemplazo parcial: seleccionar la mitad mejor de la población actual
        mitad_poblacion_actual = np.argsort([calcular_aptitud(ind) for ind in poblacion])[::-1][:poblacion_size // 2]
        poblacion = np.concatenate((poblacion[mitad_poblacion_actual],
                                   nueva_poblacion))
        mejor_individuo = poblacion[np.argmax([calcular_aptitud(ind) for ind in poblacion])]
        mejor_aptitud = calcular_aptitud(mejor_individuo)
        print(f'Generación {generacion + 1}: Mejor aptitud = {mejor_aptitud}, Mejor individuo = {mejor_individuo}')

    return mejor_individuo

# Ejecutar el algoritmo genético
mejor_solucion = algoritmo_genetico()

print('Mejor solución encontrada:')
for i, cantidad in enumerate(mejor_solucion):
    print(f'{ingredientes[i]}: {cantidad:.2f} g')

print('\nInformación nutricional:')
proteina_total, carbohidrato_total, grasa_total, calorias_total = calcular_nutricion(mejor_solucion)
print(f'Proteínas: {proteina_total:.2f} g')
print(f'Carbohidratos: {carbohidrato_total:.2f} g')
print(f'Grasas: {grasa_total:.2f} g')
print(f'Calorías: {calorias_total:.2f} kcal')

costo_total = np.sum(mejor_solucion * precios)
print(f'\nCosto total: ${costo_total:.2f}')


Generación 1: Mejor aptitud = 0.08222656273953287, Mejor individuo = [13.93081419 26.36252886 26.53887214  1.93718203]
Generación 2: Mejor aptitud = 0.09455954289489842, Mejor individuo = [30.57687202 33.52442446 13.50358494  1.47409652]
Generación 3: Mejor aptitud = 0.12292571518572765, Mejor individuo = [30.57687202 33.52442446 13.50358494  3.93909942]
Generación 4: Mejor aptitud = 0.12292571518572765, Mejor individuo = [30.57687202 33.52442446 13.50358494  3.93909942]
Generación 5: Mejor aptitud = 0.1291272343209375, Mejor individuo = [15.80284646 33.52442446 13.50358494  3.88604276]
Generación 6: Mejor aptitud = 0.1291272343209375, Mejor individuo = [15.80284646 33.52442446 13.50358494  3.88604276]
Generación 7: Mejor aptitud = 0.14274915320098316, Mejor individuo = [13.93081419 34.89291291 13.50358494  3.93909942]
Generación 8: Mejor aptitud = 0.15335274275542826, Mejor individuo = [13.93081419 34.89291291 14.1090622   3.93909942]
Generación 9: Mejor aptitud = 0.15425127710134756,